travis:
  secure:
    BINSTAR_TOKEN: CAObCI6MUj12cmOMtGtR9q9EZQP8kdBQwROJFT5pPtvPlc23PQUGS6bpxEF2wOYEEaGeVhezfprr+oAdhgvGKj1cEAt7qdrDo5FlELhn6KyVmSr0djXQkPOdeNyAQJXLKhich4JrgnbePpfoWxGHtO7lNpoJqlB6V3TcSMEPvQlSgF10VfYgNI1ic9ec5/mg2qIcQT4u+Wf7/yJCflMhMlyxfnawT4DATUIPt2MMwRdhwXgP/ZmdkFnnuT8h4mwzcT11FxCB45SJ6ShaUR1A8BpHNLUwN9VVSnaODig/SnQJELILZ3Z9+odC4ACrXSlrExSEHCaqFljHHNGcoLF4pWG5tFINmuhdQivoH4lV1jSwIA9KAGe5l7XSWgYNfx3nao3QLy0c2J1y/x0PLERMjXGD+v5M8J390pej335hrTX/Nh2w7DoWVzBRB9N69KwZvktvmNS1p2Cg9OZSCN3zX3aCG56/DzE0+RcrVkqO2KUFUXj5vtZKd2ijH9TumVML5kRZoRdpgnv9A0h06RPT+qSnwTr86eDqxx1x2p1Vtc+gxOwAPFJO4zf4lhxIkCCIbVXQhTQSH1r96QSbpQFWsifNSeWeopMlTIAgIoF6PXl71VtJJg4itl2HHZMlFkKwIi+OK3ysVPswV9l0vY8cv6/0ClV2iZCd4O0dEjp6jtA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
