travis:
  secure:
    BINSTAR_TOKEN: WpTztWRGcbEhxQ89owaunJ+2QvbQykDxA7IjFxRUmXObfk/gASOZDD9WDLmrrpO9oNESF8+UKvoOq5nG5Rhm/lAWMQFfUzp7v1tQ0WS/ej2Vo0h2ZegeIB30gGa5i40XvlBIbPTMxZNhi3KGfxFS0ERNdVXMx1lu7B1657qMln8E2d8km+PWCD/kz1Ujvnho51HMsYoxinIjQvLGprRMwz1XTq0rZNiSEK3p9G4tqaG5hRvr7Yl/dzyanDm0kpljDQhLGfwVblVb+jk9UtG11ErhcNozj/rqrxpQmGwMaPQTLJPB9MWU3oQksMhq5ImpgOxGkOaXBZZsvXuMXqHU23OSn68dh753jvB7QmissL1d/l8oJJlkXpAY4p4SmuB/X3TedB1Wk0XpQDQDXFqVEcEnSUURw6VWXu6/s1sx/7yd81Zp5dwqKXbGoeAXZEZPbWnVFMJngtd+tzEOe+fufdITA0hgeu/pBx/TcQk/xBkRJ4VJo4HLntc7mK7pY1Ttqw6nSFtzkryv7j9iCUZfWUE7Wk6BbjlH8TDJFdCj99e3vl21g74AlQl6t04Q0y5euku+IFxHWBkSh4JZ2teOrkMe+Bbw17yt5wZFOvIqf8+WM4Lr9qHO1ntbmRB19wGPSXL6mDLcc0dZegdYfH7ioOsj2Kq24mFZTKUYUkVbNWI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
