travis:
  secure:
    BINSTAR_TOKEN: J0aIrWjagYIufvbIZvNggwGBdMH8914+Yycm8yjXCl1DFiDrHsGHNp9ExLNz6y840Rfy24+dTsHp3Wltd1ZV6LsQupQpd5U0vclFxKtosOjEnY3CXDo5Qig2pzstAgUlA7Y+xjlI16hWrh2F9zrqtZQGpi6FH+7IaBQT4trqkiyyewJA4fxTpy7NO+jYN+THNheUdFRqpcAvFPrGjmTr2RC7tpS3B07BZbgLhjRaF20UHGaSKM3iNVwK0JRP3y1/BGin1LMe80elfZVyVIcbl//gbOxkog1tCCTOMxMSxydVQQNaZhKcNoLwXABjVcRHWKRFrw+dbAHExSyJNuylH3A0H3f6EC0v+cYERWXupo7vpPAvumwt7w6usasxMG3Zj8/NJKirGaf9R7Upbfkh+Vy7jzIuljoq3DEVTOHRnyH5mPUwBBb0ugQNI8iVOgyNiF+9pA8f1hG15QW7rMYQMyYvwrOev63bmnYrdfEMhxwMGbry0xhIgjll6eI99eA0XY5Qk/JEbB80ysVOL6LkpO/JOLi591Fm5m3JrsclnUE9zGHkg5m3kLkEmNfmjtX5ip+DJa5scQ33NNTIJ9AL54Tcwv5nJQBgppZTWLDvQCYua2ndk2FCRWlJg3iqNLShacHRbjRtBMfDGL26SLZOLY1Q7NUj7OLusdFRTwSTqak=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
